export enum RunEvents {
  FETCH_SUIT_START = 'FETCH_SUIT_START',
  FETCH_SUIT_DONE = 'FETCH_SUIT_DONE',
  FETCH_SUIT_ERROR = 'FETCH_SUIT_ERROR',

  REQ_RUN_START = 'REQ_RUN_START',
  REQ_RUN_END = 'REQ_RUN_END',

  SELECT_SUIT = 'SELECT_SUIT',

  TEST_START = 'TEST_START',
  TEST_FINISHED = 'TEST_FINISHED'
}